/*
Multiples of 3 and 5
If we list all the natural numbers below 10 that are multiples 
of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 
23.
Find the sum of all the multiples of 3 or 5 below 1000.
*/
var problem1 = function(number) {
  var sum = 0;
  for(var i = 1; i < number; i++){
    if(i % 3 === 0) || (i % 5 === 0){
      sum+=i;
    }
  }
  return sum;
}

/*
Each new term in the Fibonacci sequence is generated by adding 
the previous two terms. By starting with 1 and 2, the first 10 
terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values 
do not exceed four million, find the sum of the even-valued 
terms.
*/
var problem2 = function(number) {
  var num = 1;
  var temp_num = 2;
  var sum = num + temp_num;
  var total = 2;
  
  while(sum < number) {
    if(sum % 2 === 0) {
      total += sum;
    }
    console.log(sum);
    num = temp_num;
    temp_num = sum;
    sum = num + temp_num;
  }
  return total;
}

problem1(1000);
problem2(4000000);